### ISSUE TITLE
Run server on separate ws server

### ISSUE THREAD

**Issue by dennisdupont** [yokyak/react-agent#115]
Is there a way to server the react code from one web server and the websockets from another?  I am using nginx to split functions between different back end services.  

For instance in a rest api scenario I would configure the /api path in nginx to go to a different upstream that handles just rest calls vs the root path which delivers the react application.

**Comment by tskittles** [comment]
That’s completely possible. As long as you set up your services correctly, it should work. That is, use one service to host the application and one service with React Agent.
